#!/usr/bin/env bash
# Good 'Nuff main business menu

BIN="$HOME/.local/bin"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
CYAN="$(tput setaf 6)"
RESET="$(tput sgr0)"
BOLD="$(tput bold)"
DIM="$(tput dim)"

center() {
    local text="$1"
    local cols
    cols=$(tput cols)
    printf "%*s\n" $(( (cols + ${#text}) / 2 )) "$text"
}

show_title() {
    local cols
    cols=$(tput cols)

    local line
    line=$(printf '%*s' "$cols" '' | tr ' ' '=')

    local title="GOOD 'NUFF MOBILE GARAGE"

    printf "%s\n" "${BOLD}${CYAN}${line}${RESET}"
    printf "%s\n" "${BOLD}${CYAN}${line}${RESET}"
    center "${BOLD}${CYAN}${title}${RESET}"
    printf "%s\n" "${BOLD}${CYAN}${line}${RESET}"
    printf "%s\n" "${BOLD}${CYAN}${line}${RESET}"
    echo
}